### ISSUE TITLE
postgresql::ruby not running apt-get update

### ISSUE THREAD

**Issue by kpettijohn** [hw-cookbooks/postgresql#171]
I was having issues getting libpq-dev to install on Ubuntu14. Even after making sure to specify `recipe[apt::default]` first in the run list. I noticed the ruby recipe (https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/ruby.rb) was using `run_action` and would to run before `recipe[apt::default]` was being run. 

This could be a odd use case as my base vagrant image already has the file `/var/lib/apt/periodic/update-success-stamp` (last updated on July 6th) so the check being performed here https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/ruby.rb#L32 was always skipping the `apt-update` call from being triggered. 

I added a quick work around for my situation here:
https://github.com/kpettijohn/postgresql/blob/feature/apt-update-on-time/recipes/ruby.rb#L33 

Basically I just check that `apt-get update` was run with 24 hours. I don't think this is really the best solution but I thought it would be worth creating a issue to give this some visibility if others run into the problem. 

```
Starting Chef Client, version 11.14.2
resolving cookbooks for run list: ["apt::default", "mycookbook"]
Synchronizing Cookbooks:
  - apt
  - nginx
  - beanstalkd
  - bluepill
  - ohai
  - yum-epel
  - database
  - runit
  - build-essential
  - openssl
  - rsyslog
  - yum
  - aws
  - mysql-chef_gem
  - chef-sugar
  - mysql
  - yum-mysql-community
  - xfs
  - mycookbook
  - postgresql
Compiling Cookbooks...
Recipe: ohai::default
  * remote_directory[/etc/chef/ohai_plugins for cookbook ohai] action create
    - create new directory /etc/chef/ohai_plugins
    - change mode from '' to '0755'
  Recipe: <Dynamically Defined Resource>
    * cookbook_file[/etc/chef/ohai_plugins/README] action create
      - create new file /etc/chef/ohai_plugins/README
      - update content in file /etc/chef/ohai_plugins/README from none to 775fa7
      --- /etc/chef/ohai_plugins/README	2014-08-25 16:02:33.641378345 -0700
      +++ /tmp/.README20140825-6943-3v6zpq	2014-08-25 16:02:34.033350556 -0700
      @@ -1 +1,2 @@
      +This directory contains custom plugins for Ohai.
      - change mode from '' to '0644'

Recipe: ohai::default
  * ohai[custom_plugins] action reload
    - re-run ohai and merge results into node attributes
[2014-08-25T16:02:46-07:00] WARN: Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)
[2014-08-25T16:02:46-07:00] WARN: Previous service[nginx]: /home/vagrant/.chef/local-mode-cache/cache/cookbooks/nginx/recipes/package.rb:46:in `from_file'
[2014-08-25T16:02:46-07:00] WARN: Current  service[nginx]: /home/vagrant/.chef/local-mode-cache/cache/cookbooks/nginx/recipes/default.rb:24:in `from_file'
Recipe: build-essential::_debian
  * package[autoconf] action install (up to date)
  * package[binutils-doc] action install (up to date)
  * package[bison] action install (up to date)
  * package[build-essential] action install (up to date)
  * package[flex] action install (up to date)
  * package[gettext] action install (up to date)
  * package[ncurses-dev] action install (up to date)
Recipe: postgresql::apt_pgdg_postgresql
  * file[remove deprecated Pitti PPA apt repository] action delete (up to date)
  * apt_repository[apt.postgresql.org] action add
    * remote_file[/home/vagrant/.chef/local-mode-cache/cache/ACCC4CF8.asc] action create (up to date)
    * execute[install-key ACCC4CF8.asc] action run (skipped due to not_if)
    * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
    * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
    * execute[apt-get update] action nothing (skipped due to action :nothing)
    * file[/etc/apt/sources.list.d/apt.postgresql.org.list] action create (up to date)
     (up to date)
Recipe: postgresql::client
  * package[postgresql-client-9.3] action install (up to date)
  * package[libpq-dev] action install

    ================================================================================
    Error executing action `install` on resource 'package[libpq-dev]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '100'
    ---- Begin output of apt-get -q -y install libpq-dev=9.3.5-1.pgdg14.04+1 ----
    STDOUT: Reading package lists...
    Building dependency tree...
    Reading state information...
    The following extra packages will be installed:
      comerr-dev krb5-multidev libgssrpc4 libkadm5clnt-mit9 libkadm5srv-mit9
      libkdb5-7 libpq5 libssl-dev libssl-doc zlib1g-dev
    Suggested packages:
      doc-base krb5-doc krb5-user postgresql-doc-9.3
    The following NEW packages will be installed:
      comerr-dev krb5-multidev libgssrpc4 libkadm5clnt-mit9 libkadm5srv-mit9
      libkdb5-7 libpq-dev libssl-dev libssl-doc zlib1g-dev
    The following packages will be upgraded:
      libpq5
    1 upgraded, 10 newly installed, 0 to remove and 2 not upgraded.
    Need to get 2,032 kB/2,828 kB of archives.
    After this operation, 11.4 MB of additional disk space will be used.
    Err http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libssl-dev amd64 1.0.1f-1ubuntu2.4
      404  Not Found [IP: 91.189.91.14 80]
    Err http://security.ubuntu.com/ubuntu/ trusty-security/main libssl-dev amd64 1.0.1f-1ubuntu2.4
      404  Not Found [IP: 91.189.92.201 80]
    Err http://security.ubuntu.com/ubuntu/ trusty-security/main libssl-doc all 1.0.1f-1ubuntu2.4
      404  Not Found [IP: 91.189.92.201 80]
    STDERR: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.0.1f-1ubuntu2.4_amd64.deb  404  Not Found [IP: 91.189.92.201 80]

    E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-doc_1.0.1f-1ubuntu2.4_all.deb  404  Not Found [IP: 91.189.92.201 80]

    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    ---- End output of apt-get -q -y install libpq-dev=9.3.5-1.pgdg14.04+1 ----
    Ran apt-get -q -y install libpq-dev=9.3.5-1.pgdg14.04+1 returned 100

    Cookbook Trace:
    ---------------
    /home/vagrant/.chef/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:54:in `block in from_file'
    /home/vagrant/.chef/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:53:in `each'
    /home/vagrant/.chef/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:53:in `rescue in from_file'
    /home/vagrant/.chef/local-mode-cache/cache/cookbooks/postgresql/recipes/ruby.rb:24:in `from_file'
    /home/vagrant/.chef/local-mode-cache/cache/cookbooks/mycookbook/recipes/default.rb:20:in `from_file'

    Resource Declaration:
    ---------------------
    # In /home/vagrant/.chef/local-mode-cache/cache/cookbooks/postgresql/recipes/client.rb

     36:   package pg_pack
     37:

    Compiled Resource:
    ------------------
    # Declared in /home/vagrant/.chef/local-mode-cache/cache/cookbooks/postgresql/recipes/client.rb:36:in `block in from_file'

    package("libpq-dev") do
      action :install
      retries 0
      retry_delay 2
      guard_interpreter :default
      package_name "libpq-dev"
      version "9.3.5-1.pgdg14.04+1"
      timeout 900
      cookbook_name "postgresql"
      recipe_name "client"
    end
```

**Comment by RLovelett** [comment]
I notice that this issue is still open, does this mean this is being recognized as an issue in the `postgresql` cookbook and an fix will eventually be provided as part of the cookbook? Or should we assume that this is a configuration "bug" and we, the consumers of this cookbook, should be incorporating the work-arounds provided by @hulu1522 into our cookbooks?

(Obviously in the short term @hulu1522's fixes need to be used. I'm just wondering what the long-term solution is expected to be.)

**Comment by kpettijohn** [comment]
@RLovelett Personally I think that because the cookbook is already attempting to update the repos at compile time [here](https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/ruby.rb#L25-L30) it would be nice to have some better logic to determine if `apt-get update` should be run at compile time or not. 

If we think it should be left up to the consumers of the cookbook then we should remove the current logic so it will fail consistently and just add a note on the README that includes some suggestions provided by @hulu1522

Just my two cents on the issue.

**Comment by hulu1522** [comment]
I guess I'll through in a few comments on this one.  The biggest issue with the Ruby recipe is that it needs to compile the gem.  That requires `build-essential` cookbook to run.  Since you are forcing that to run at compile time we need to make sure `apt` is run before it in order for the package repo's to be updated.  I would almost suggest removing both the [`build-essential`](https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/ruby.rb#L32-L33) and [`apt`](https://github.com/hw-cookbooks/postgresql/blob/develop/recipes/ruby.rb#L25-L30) from the recipe and allow the end user to install them as a base.  Just make sure people know about the change and how to fulfill the dependancies of using the Ruby recipe.  @kpettijohn @RLovelett

**Comment by slyness** [comment]
`postgresql::ruby` is building the pg gem fine in current cookbook releases.

**Comment by rberger** [comment]
Still having this problem with postgresql release 4.0.6
