### ISSUE TITLE
Error executing action `start` on resource 'service[postgresql]' on CentOS 6.5

### ISSUE THREAD

**Issue by ozzyogkush** [hw-cookbooks/postgresql#245]
My wrapper recipe updates yum, installs yum-remi and yum-epel, and then installs `postgresql::server`, currently using CentOS 6.5 as that what my hosted service uses, and everything seems to work except when it gets to line 90 of the [`postgresql::server_redhat` recipe](https://github.com/hw-cookbooks/postgresql/blob/v3.4.18/recipes/server_redhat.rb#L90). I'm not quite sure what I'm doing wrong here.

This is being run as part of a `kitchen converge`:

```
Recipe: postgresql::server_redhat
         * service[postgresql] action enable[2015-04-06T02:34:25+00:00] INFO: Processing service[postgresql] action enable (postgresql::server_redhat line 90)
       [2015-04-06T02:34:25+00:00] INFO: service[postgresql] enabled
       
           - enable service service[postgresql]
       
         * service[postgresql] action start[2015-04-06T02:34:25+00:00] INFO: Processing service[postgresql] action start (postgresql::server_redhat line 90)
       
           
           ================================================================================
           Error executing action `start` on resource 'service[postgresql]'
           ================================================================================
           
       
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/service postgresql start ----
           STDOUT: Starting postgresql service: [FAILED]
           STDERR: 
           ---- End output of /sbin/service postgresql start ----
           Ran /sbin/service postgresql start returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/postgresql/recipes/server_redhat.rb
           
            90: service "postgresql" do
            91:   service_name svc_name
            92:   supports :restart => true, :status => true, :reload => true
            93:   action [:enable, :start]
            94: end
           
       
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/postgresql/recipes/server_redhat.rb:90:in `from_file'
           
           service("postgresql") do
             action [:enable, :start]
             updated true
             supports {:restart=>true, :status=>true, :reload=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "postgresql"
             enabled true
             pattern "postgresql"
             declared_type :service
             cookbook_name "postgresql"
             recipe_name "server_redhat"
           end
           
       
       [2015-04-06T02:34:27+00:00] INFO: Running queued delayed notifications before re-raising exception
       [2015-04-06T02:34:27+00:00] INFO: template[/etc/sysconfig/pgsql/postgresql] sending restart action to service[postgresql] (delayed)
         * service[postgresql] action restart
       [2015-04-06T02:34:27+00:00] INFO: Processing service[postgresql] action restart (postgresql::server_redhat line 90)
       
           
           ================================================================================
       
           Error executing action `restart` on resource 'service[postgresql]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/service postgresql restart ----
           STDOUT: Stopping postgresql service: [  OK  ]
           Starting postgresql service: [FAILED]
           STDERR: 
           ---- End output of /sbin/service postgresql restart ----
           Ran /sbin/service postgresql restart returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/postgresql/recipes/server_redhat.rb
           
            90: service "postgresql" do
            91:   service_name svc_name
            92:   supports :restart => true, :status => true, :reload => true
            93:   action [:enable, :start]
            94: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/postgresql/recipes/server_redhat.rb:90:in `from_file'
           
           service("postgresql") do
             action [:enable, :start]
             updated true
             supports {:restart=>true, :status=>true, :reload=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "postgresql"
             enabled true
             pattern "postgresql"
             declared_type :service
           
         cookbook_name "postgresql"
             recipe_name "server_redhat"
           end
```

Output of chef-stacktrace.out:

```
Generated at 2015-04-06 02:34:29 +0000
Chef::Exceptions::MultipleFailures: Chef::Exceptions::MultipleFailures
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:278:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:265:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:66:in `shell_out_with_systems_locale!'
/opt/chef/embedded/apps/chef/lib/chef/provider/service/init.rb:59:in `start_service'
/opt/chef/embedded/apps/chef/lib/chef/provider/service.rb:90:in `block in action_start'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/service.rb:89:in `action_start'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:449:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>'
```

**Comment by ozzyogkush** [comment]
This is very frustrating and is blocking me from being able to move forward with a project.

**Comment by slyness** [comment]
Do you have a PR open that might help resolve this issue?

**Comment by ozzyogkush** [comment]
None that I've written, but a few possibilities were mentioned in #167.

**Comment by peterjmit** [comment]
To add some further information here I am seeing the same error when trying to install 9.4 on Centos 6.5.

I have added the links in #246 to enable the 9.4 download, the rest of my attributes are as follows

```ruby
node.default['postgresql']['enable_pgdg_yum'] = true
node.default['postgresql']['version'] = '9.4'
node.default['postgresql']['dir'] = "/var/lib/pgsql/9.4/data"
node.default['postgresql']['client']['packages'] = ["postgresql94", "postgresql94-devel"]
node.default['postgresql']['server']['packages'] = ["postgresql94-server"]
node.default['postgresql']['server']['service_name'] = "postgresql-9.4"
node.default['postgresql']['contrib']['packages'] = ["postgresql94-contrib"]
```

The error I get in `/var/lib/pgsql/9.4/pgstartup.log` is 

```
LOG:  skipping missing configuration file "/var/lib/pgsql/data/postgresql.auto.conf"
FATAL:  data directory "/var/lib/pgsql/data" does not exist
LOG:  skipping missing configuration file "/var/lib/pgsql/data/postgresql.auto.conf"
FATAL:  data directory "/var/lib/pgsql/data" does not exist
LOG:  skipping missing configuration file "/var/lib/pgsql/data/postgresql.auto.conf"
FATAL:  data directory "/var/lib/pgsql/data" does not exist
```

Despite previous logs suggesting the data dir being configured correctly

> creating template1 database in /var/lib/pgsql/9.4/data/base/1 ... ok

I'll do some more digging and see if I can figure it out

**Comment by ozzyogkush** [comment]
https://github.com/hw-cookbooks/postgresql/pull/269

**Comment by merqlove** [comment]
@ozzyogkush I have tested this PR with 6.6 & 7+.
- This version works well on my nodes: CentOS 6.6 (clean build), 9.3 or 9.4.
- >=7 fix works only on 7+, 9.3+. 
- I have not tested it with 7+ & PG 9.4+

**Comment by ozzyogkush** [comment]
I've run your PR on my project, still getting the same errors.

**Comment by patcon** [comment]
@ozzyogkush you probably want to post your startup log some place, as that's where the failure is: `/var/lib/pgsql/pgstartup.log`

I had to set the shared_buffers really low (24MB rather than the default 32MB for centos) to get past something similar to what you're seeing.

**Comment by slyness** [comment]
It seems this was a localized error which hopefully you were able to move past. For correctly configured postgresql the service resource in the latest cookbook is working without error.
