### ISSUE TITLE
Warning when installing rubygem

### ISSUE THREAD

**Issue by robkinyon** [hw-cookbooks/postgresql#296]
This is seen when installing `postgresql::ruby` using Vagrant 1.7.4, vagrant-librarian-chef plugin (0.2.1), and postgresql cookbook 3.4.20.
```
==> default: Deprecated features used!
==> default:   chef_gem[pg] chef_gem compile_time installation is deprecated at 1 location:
==> default:     - /tmp/vagrant-chef/420decd1ec109c62b1f6835a073d8a9a/cookbooks/postgresql/recipes/ruby.rb:55:in `rescue in from_file'
==> default:   chef_gem[pg] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
==> default:     - /tmp/vagrant-chef/420decd1ec109c62b1f6835a073d8a9a/cookbooks/postgresql/recipes/ruby.rb:55:in `rescue in from_file'
==> default:   chef_gem[pg] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
==> default:     - /tmp/vagrant-chef/420decd1ec109c62b1f6835a073d8a9a/cookbooks/postgresql/recipes/ruby.rb:55:in `rescue in from_file'
```

**Comment by slyness** [comment]
corrected in #346 . This will be included in the next release.
